# Q- Why is Numpy faster than List?

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## 0-D Array

In [5]:
arr0 = np.array(45)
print(arr0)

45


## 1-D Array

In [6]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


## 2-D Array

In [7]:
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]


## 3-D Array

In [8]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
# check the dimension of array
arr2.ndim

2

In [10]:
# create a higher dimmensional array
arr = np.array([1, 2, 3, 4], ndmin=6)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


# Accessing Element

In [11]:
# 1-D array
print(arr1[0])

# 2-D array
print(arr2[1,1])

# 3-D array
print(arr3[1,1,0])

# negative indexing
print(arr3[0,0,-1])

1
2
4
3


# Shape of array

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr_shape = arr.shape
print(arr_shape)
print(arr_shape[1])

(2, 4)
4


# Data types

In [13]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [15]:
arr = np.array([1, 2, 3, 4], dtype='int8') # int8, int16, int32

print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [16]:
# convert array to new data type

arr = np.array([1.3, 2.5, 3.6])
print(arr)
print(arr.dtype)

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1.3 2.5 3.6]
float64
[1 2 3]
int32


# Copy and View

In [18]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [19]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Reshaping array

In [22]:
# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
# 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
# 1D to 3D but shape of last dimmension is unknown
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Flattening- from N-D to 1D

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Joining Arrays

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[1 2 3 4 5 6]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Stacking

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
# Horizontal Stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [30]:
# Vertical Stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


# Assignment

In [31]:
a=[10,12,11,12,13,10]
b=[1,2,6,2,47,85,2,45,2,1]

s1 = set(a)
s2 = set(b)
print(s1)
print(s2)

{10, 11, 12, 13}
{1, 2, 6, 45, 47, 85}


In [32]:
A_list=[]
for i in s1:
    A_list.append((i, a.count(i)))

print(A_list)

B_list=[]
for i in s2:
    B_list.append((i, b.count(i)))

print(B_list)

[(10, 2), (11, 1), (12, 2), (13, 1)]
[(1, 2), (2, 4), (6, 1), (45, 1), (47, 1), (85, 1)]


In [33]:
d={}
d["List A"]=A_list
d["List B"]=B_list
d

{'List A': [(10, 2), (11, 1), (12, 2), (13, 1)],
 'List B': [(1, 2), (2, 4), (6, 1), (45, 1), (47, 1), (85, 1)]}